// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutUsDocumentDataSlicesSlice = AboutUsSlice;

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * Slice Zone field in *About Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice> /**
   * Meta Title field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

type BlogpostDocumentDataSlicesSlice = BlogpostSlice;

/**
 * Content for Blogpost documents
 */
interface BlogpostDocumentData {
  /**
   * Slice Zone field in *Blogpost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogpost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blogpost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

type ContinentTextDocumentDataSlicesSlice = ContinentsTextSlice;

/**
 * Content for Continent text documents
 */
interface ContinentTextDocumentData {
  /**
   * Continent Description field in *Continent text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continent_text.continent_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  continent_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Continent text*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: continent_text.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContinentTextDocumentDataSlicesSlice> /**
   * Meta Title field in *Continent text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: continent_text.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Continent text*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: continent_text.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Continent text*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: continent_text.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Continent text document from Prismic
 *
 * - **API ID**: `continent_text`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContinentTextDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContinentTextDocumentData>,
    "continent_text",
    Lang
  >;

type DestinationsDocumentDataSlicesSlice = DestinationPageSlice;

/**
 * Content for destination documents
 */
interface DestinationsDocumentData {
  /**
   * meta_title field in *destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of the place
   * - **API ID Path**: destinations.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Continent field in *destination*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: destinations.continent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  continent: prismic.SelectField<
    | "Europe"
    | "Asia"
    | "South America"
    | "North America"
    | "Africa"
    | "Australia"
  >;

  /**
   * meta_description field in *destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description
   * - **API ID Path**: destinations.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * country_image field in *destination*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destinations.country_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  country_image: prismic.ImageField<never>;

  /**
   * Specific Date field in *destination*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Offer with fixed dates
   * - **API ID Path**: destinations.specific_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  specific_date: prismic.DateField;

  /**
   * Country field in *destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: France
   * - **API ID Path**: destinations.country
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country: prismic.KeyTextField;

  /**
   * City field in *destination*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City
   * - **API ID Path**: destinations.city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * destination tag field in *destination*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: destinations.destination_tag
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination_tag: prismic.ContentRelationshipField<"destinations">;

  /**
   * Slice Zone field in *destination*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: destinations.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DestinationsDocumentDataSlicesSlice>;
}

/**
 * destination document from Prismic
 *
 * - **API ID**: `destinations`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DestinationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DestinationsDocumentData>,
    "destinations",
    Lang
  >;

type FooterDocumentDataSlicesSlice = FooterSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Meta Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderimageDocumentDataSlicesSlice = HeaderSlice;

/**
 * Content for HeaderImage documents
 */
interface HeaderimageDocumentData {
  /**
   * Slice Zone field in *HeaderImage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: headerimage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderimageDocumentDataSlicesSlice> /**
   * Meta Title field in *HeaderImage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: headerimage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HeaderImage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: headerimage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HeaderImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headerimage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HeaderImage document from Prismic
 *
 * - **API ID**: `headerimage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderimageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderimageDocumentData>,
    "headerimage",
    Lang
  >;

type MenuDocumentDataSlicesSlice = MainMenuSlice;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Slice Zone field in *Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MenuDocumentDataSlicesSlice> /**
   * Meta Title field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: menu.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: menu.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type NewsletterDocumentDataSlicesSlice = NewsletterSlice;

/**
 * Content for Newsletter documents
 */
interface NewsletterDocumentData {
  /**
   * Slice Zone field in *Newsletter*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsletterDocumentDataSlicesSlice> /**
   * Meta Title field in *Newsletter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: newsletter.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Newsletter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: newsletter.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Newsletter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Newsletter document from Prismic
 *
 * - **API ID**: `newsletter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsletterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NewsletterDocumentData>,
    "newsletter",
    Lang
  >;

type TestimonialsDocumentDataSlicesSlice = TestimonialSlice;

/**
 * Content for Testimonials documents
 */
interface TestimonialsDocumentData {
  /**
   * Slice Zone field in *Testimonials*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestimonialsDocumentDataSlicesSlice> /**
   * Meta Title field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: testimonials.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: testimonials.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Testimonials document from Prismic
 *
 * - **API ID**: `testimonials`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialsDocumentData>,
    "testimonials",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | BlogpostDocument
  | ContinentTextDocument
  | DestinationsDocument
  | FooterDocument
  | HeaderimageDocument
  | MenuDocument
  | NewsletterDocument
  | TestimonialsDocument;

/**
 * Item in *AboutUs → Default → Primary → List Items*
 */
export interface AboutUsSliceDefaultPrimaryListItemsItem {
  /**
   * List Icon field in *AboutUs → Default → Primary → List Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.list_items[].list_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  list_icon: prismic.ImageField<never>;

  /**
   * List Title field in *AboutUs → Default → Primary → List Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.list_items[].list_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list_title: prismic.KeyTextField;

  /**
   * List Description field in *AboutUs → Default → Primary → List Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.list_items[].list_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list_description: prismic.KeyTextField;
}

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * About Us Image field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.about_us_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  about_us_image: prismic.ImageField<never>;

  /**
   * About Text field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Plan your trips with us
   * - **API ID Path**: about_us.default.primary.about_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_text: prismic.RichTextField;

  /**
   * List Items field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.list_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list_items: prismic.GroupField<
    Simplify<AboutUsSliceDefaultPrimaryListItemsItem>
  >;

  /**
   * button link field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to page
   * - **API ID Path**: about_us.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>;

/**
 * Primary content in *Blogpost → Default → Primary*
 */
export interface BlogpostSliceDefaultPrimary {
  /**
   * Blog image field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.blog_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blog_image: prismic.ImageField<never>;

  /**
   * Title field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Date field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Author field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Minutes field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.minutes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  minutes: prismic.KeyTextField;

  /**
   * Link field in *Blogpost → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Blogpost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogpostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogpostSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blogpost*
 */
type BlogpostSliceVariation = BlogpostSliceDefault;

/**
 * Blogpost Shared Slice
 *
 * - **API ID**: `blogpost`
 * - **Description**: Blogpost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogpostSlice = prismic.SharedSlice<
  "blogpost",
  BlogpostSliceVariation
>;

/**
 * Primary content in *ContinentsText → Default → Primary*
 */
export interface ContinentsTextSliceDefaultPrimary {
  /**
   * Heading text field in *ContinentsText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continents_text.default.primary.heading_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading_text: prismic.KeyTextField;

  /**
   * Last card text field in *ContinentsText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: continents_text.default.primary.last_card_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  last_card_text: prismic.KeyTextField;
}

/**
 * Default variation for ContinentsText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContinentsTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContinentsTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContinentsText*
 */
type ContinentsTextSliceVariation = ContinentsTextSliceDefault;

/**
 * ContinentsText Shared Slice
 *
 * - **API ID**: `continents_text`
 * - **Description**: ContinentsText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContinentsTextSlice = prismic.SharedSlice<
  "continents_text",
  ContinentsTextSliceVariation
>;

/**
 * Item in *DestinationPage → Default → Primary → Gallery*
 */
export interface DestinationPageSliceDefaultPrimaryGalleryItem {
  /**
   * ImageGallery field in *DestinationPage → Default → Primary → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_page.default.primary.gallery[].imagegallery
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagegallery: prismic.ImageField<never>;
}

/**
 * Primary content in *DestinationPage → Default → Primary*
 */
export interface DestinationPageSliceDefaultPrimary {
  /**
   * Header Image field in *DestinationPage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_page.default.primary.header_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * Gallery field in *DestinationPage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_page.default.primary.gallery[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<
    Simplify<DestinationPageSliceDefaultPrimaryGalleryItem>
  >;

  /**
   * destination field in *DestinationPage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_page.default.primary.destination
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination: prismic.KeyTextField;

  /**
   * Location field in *DestinationPage → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: destination_page.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;
}

/**
 * Default variation for DestinationPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DestinationPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DestinationPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DestinationPage*
 */
type DestinationPageSliceVariation = DestinationPageSliceDefault;

/**
 * DestinationPage Shared Slice
 *
 * - **API ID**: `destination_page`
 * - **Description**: DestinationPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DestinationPageSlice = prismic.SharedSlice<
  "destination_page",
  DestinationPageSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Social Media*
 */
export interface FooterSliceDefaultPrimarySocialMediaItem {
  /**
   * Social Media Icon field in *Footer → Default → Primary → Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_media[].social_media_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_icon: prismic.ImageField<never>;

  /**
   * Social Media link field in *Footer → Default → Primary → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_media[].social_media_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_link: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Support*
 */
export interface FooterSliceDefaultPrimarySupportItem {
  /**
   * Support Sub Menu field in *Footer → Default → Primary → Support*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.support[].support_sub_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  support_sub_menu: prismic.KeyTextField;

  /**
   * Support links field in *Footer → Default → Primary → Support*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.support[].support_links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  support_links: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Company*
 */
export interface FooterSliceDefaultPrimaryCompanyItem {
  /**
   * Company Sub Menu field in *Footer → Default → Primary → Company*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.company[].company_sub_menu
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_sub_menu: prismic.KeyTextField;

  /**
   * Company links field in *Footer → Default → Primary → Company*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.company[].company_links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_links: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Services*
 */
export interface FooterSliceDefaultPrimaryServicesItem {
  /**
   * Services Sub items field in *Footer → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.services[].services_sub_items
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  services_sub_items: prismic.KeyTextField;

  /**
   * Services links field in *Footer → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.services[].services_links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  services_links: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Legal*
 */
export interface FooterSliceDefaultPrimaryLegalItem {
  /**
   * Legal Sub Items field in *Footer → Default → Primary → Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal[].legal_sub_items
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  legal_sub_items: prismic.KeyTextField;

  /**
   * Legal Sub Links field in *Footer → Default → Primary → Legal*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal[].legal_sub_links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  legal_sub_links: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Footer Menu*
 */
export interface FooterSliceDefaultPrimaryFooterMenuItem {
  /**
   * Footer Item field in *Footer → Default → Primary → Footer Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footer_menu[].footer_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_item: prismic.KeyTextField;

  /**
   * Footer Link field in *Footer → Default → Primary → Footer Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footer_menu[].footer_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_link: prismic.LinkField;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Phone Number field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Address field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Working Hours field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.working_hours
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  working_hours: prismic.KeyTextField;

  /**
   * Email Address field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.email_address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_address: prismic.KeyTextField;

  /**
   * Social Media field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimarySocialMediaItem>
  >;

  /**
   * Support field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.support[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  support: prismic.GroupField<Simplify<FooterSliceDefaultPrimarySupportItem>>;

  /**
   * Company field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.company[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  company: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryCompanyItem>>;

  /**
   * Services field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryServicesItem>>;

  /**
   * Legal field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLegalItem>>;

  /**
   * All Rights Reserved field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.all_rights_reserved
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  all_rights_reserved: prismic.KeyTextField;

  /**
   * Footer Menu field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footer_menu[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_menu: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryFooterMenuItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *HeaderImg → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Header Image field in *HeaderImg → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.header_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * Header Text field in *HeaderImg → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: EXPLORE
   * - **API ID Path**: header.default.primary.header_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_text: prismic.KeyTextField;

  /**
   * Sub Header field in *HeaderImg → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: the beauty of the world
   * - **API ID Path**: header.default.primary.sub_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_header: prismic.KeyTextField;
}

/**
 * Default variation for HeaderImg Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderImg*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * HeaderImg Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *MainMenu → Default → Primary → MenuLink*
 */
export interface MainMenuSliceDefaultPrimaryMenulinkItem {
  /**
   * Menu Item field in *MainMenu → Default → Primary → MenuLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Menu Item
   * - **API ID Path**: main_menu.default.primary.menulink[].menu_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_item: prismic.KeyTextField;

  /**
   * Menu link field in *MainMenu → Default → Primary → MenuLink*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Menu Item Link
   * - **API ID Path**: main_menu.default.primary.menulink[].menu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_link: prismic.LinkField;
}

/**
 * Item in *MainMenu → Sub Menu Item → Primary → MenuLink*
 */
export interface MainMenuSliceSubMenuItemPrimaryMenulinkItem {
  /**
   * Menu Item field in *MainMenu → Sub Menu Item → Primary → MenuLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Menu Item
   * - **API ID Path**: main_menu.subMenuItem.primary.menulink[].menu_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_item: prismic.KeyTextField;

  /**
   * Menu link field in *MainMenu → Sub Menu Item → Primary → MenuLink*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Menu Item Link
   * - **API ID Path**: main_menu.subMenuItem.primary.menulink[].menu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_link: prismic.LinkField;
}

/**
 * Primary content in *MainMenu → Default → Primary*
 */
export interface MainMenuSliceDefaultPrimary {
  /**
   * Logo field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * MenuLink field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.default.primary.menulink[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menulink: prismic.GroupField<
    Simplify<MainMenuSliceDefaultPrimaryMenulinkItem>
  >;

  /**
   * CTA button field in *MainMenu → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: CTA Button
   * - **API ID Path**: main_menu.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField;
}

/**
 * Default variation for MainMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainMenuSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MainMenu → Sub Menu Item → Primary*
 */
export interface MainMenuSliceSubMenuItemPrimary {
  /**
   * Logo field in *MainMenu → Sub Menu Item → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.subMenuItem.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * MenuLink field in *MainMenu → Sub Menu Item → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.subMenuItem.primary.menulink[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menulink: prismic.GroupField<
    Simplify<MainMenuSliceSubMenuItemPrimaryMenulinkItem>
  >;

  /**
   * CTA button field in *MainMenu → Sub Menu Item → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: CTA Button
   * - **API ID Path**: main_menu.subMenuItem.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField;
}

/**
 * Sub Menu Item variation for MainMenu Slice
 *
 * - **API ID**: `subMenuItem`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainMenuSliceSubMenuItem = prismic.SharedSliceVariation<
  "subMenuItem",
  Simplify<MainMenuSliceSubMenuItemPrimary>,
  never
>;

/**
 * Slice variation for *MainMenu*
 */
type MainMenuSliceVariation = MainMenuSliceDefault | MainMenuSliceSubMenuItem;

/**
 * MainMenu Shared Slice
 *
 * - **API ID**: `main_menu`
 * - **Description**: MainMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainMenuSlice = prismic.SharedSlice<
  "main_menu",
  MainMenuSliceVariation
>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * Image field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * mobile field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile: prismic.ImageField<never>;

  /**
   * Title field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * alter text field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.alter_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  alter_text: prismic.KeyTextField;

  /**
   * Button Text field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Testimonial image field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonial_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  testimonial_image: prismic.ImageField<never>;

  /**
   * Testimonial Name field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sarah W.
   * - **API ID Path**: testimonial.default.primary.testimonial_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_name: prismic.KeyTextField;

  /**
   * Persons description field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Traveller, Paris, France
   * - **API ID Path**: testimonial.default.primary.persons_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  persons_description: prismic.KeyTextField;

  /**
   * Testimonial text field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonial_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_text: prismic.KeyTextField;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      ContinentTextDocument,
      ContinentTextDocumentData,
      ContinentTextDocumentDataSlicesSlice,
      DestinationsDocument,
      DestinationsDocumentData,
      DestinationsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderimageDocument,
      HeaderimageDocumentData,
      HeaderimageDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataSlicesSlice,
      NewsletterDocument,
      NewsletterDocumentData,
      NewsletterDocumentDataSlicesSlice,
      TestimonialsDocument,
      TestimonialsDocumentData,
      TestimonialsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimaryListItemsItem,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      BlogpostSlice,
      BlogpostSliceDefaultPrimary,
      BlogpostSliceVariation,
      BlogpostSliceDefault,
      ContinentsTextSlice,
      ContinentsTextSliceDefaultPrimary,
      ContinentsTextSliceVariation,
      ContinentsTextSliceDefault,
      DestinationPageSlice,
      DestinationPageSliceDefaultPrimaryGalleryItem,
      DestinationPageSliceDefaultPrimary,
      DestinationPageSliceVariation,
      DestinationPageSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimarySocialMediaItem,
      FooterSliceDefaultPrimarySupportItem,
      FooterSliceDefaultPrimaryCompanyItem,
      FooterSliceDefaultPrimaryServicesItem,
      FooterSliceDefaultPrimaryLegalItem,
      FooterSliceDefaultPrimaryFooterMenuItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      MainMenuSlice,
      MainMenuSliceDefaultPrimaryMenulinkItem,
      MainMenuSliceDefaultPrimary,
      MainMenuSliceSubMenuItemPrimaryMenulinkItem,
      MainMenuSliceSubMenuItemPrimary,
      MainMenuSliceVariation,
      MainMenuSliceDefault,
      MainMenuSliceSubMenuItem,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
    };
  }
}
