// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  continents_text: dynamic(() => import("./ContinentsText")),
  destination_page: dynamic(() => import("./DestinationPage")),
  header: dynamic(() => import("./HeaderImg")),
  main_menu: dynamic(() => import("./MainMenu")),
  testimonial: dynamic(() => import("./Testimonial")),
};
