// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  
  destination_page: dynamic(() => import("./DestinationPage")),
  header: dynamic(() => import("./HeaderImg")),
  main_menu: dynamic(() => import("./MainMenu")),
};
